(function (global) {
  'use strict';

  var Mod = global.DFTFlowNavMod = global.DFTFlowNavMod || {};
  var Shared = Mod.Shared;
  var Analysis = Mod.Analysis;
  var Dftspec = Mod.Dftspec = Mod.Dftspec || {};
  if (!Shared || !Analysis) throw new Error('flow_nav_shared.js and flow_nav_analysis.js must be loaded before flow_nav_dftspec.js');

  function q(v) { return JSON.stringify(v == null ? '' : v); }
  function n(v) { return v == null || isNaN(Number(v)) ? '0' : String(Number(v)); }

  Dftspec.build = function build(ui, analysis) {
    analysis = analysis || Analysis.analyzeDataflow(ui);
    var pm = Shared.getProject(ui) || {};
    var lines = [];
    lines.push('# Auto-generated by modular Flow Navigator');
    lines.push('project: ' + q(pm.name || 'unnamed_project'));
    lines.push('page: ' + q(Shared.getActivePageName(ui) || 'none'));
    lines.push('');
    lines.push('modules:');
    if (!analysis.modules.length) {
      lines.push('  []');
    } else {
      for (var i = 0; i < analysis.modules.length; i++) {
        var moduleCell = analysis.modules[i];
        var name = Shared.displayNameOfCell(Shared.graphOf(ui), moduleCell) || ('MODULE_' + i);
        var rect = Shared.rectOfCell(moduleCell) || {};
        var modulePlan = analysis.interfacePlan.modulePlans[name] || { markers: [], sources: [] };
        lines.push('  - name: ' + q(name));
        lines.push('    x: ' + n(rect.x));
        lines.push('    y: ' + n(rect.y));
        lines.push('    width: ' + n(rect.width));
        lines.push('    height: ' + n(rect.height));
        lines.push('    interfaces:');
        if (!modulePlan.markers.length) lines.push('      []');
        else {
          for (var m = 0; m < modulePlan.markers.length; m++) {
            var marker = modulePlan.markers[m];
            lines.push('      - id: ' + q(marker.id));
            lines.push('        role: ' + q(marker.role));
            lines.push('        interface_type: ' + q(marker.interfaceType || ''));
            lines.push('        layer: ' + q(marker.layerName || ''));
            lines.push('        pair: ' + q(marker.pairId || ''));
            lines.push('        side: ' + q(marker.side));
            lines.push('        offset: ' + String(Number(marker.offset || 0).toFixed(4)));
            lines.push('        peer_module: ' + q(marker.peerModule || ''));
            lines.push('        orientation: ' + q(marker.orientation || ''));
            lines.push('        source_instance: ' + q(marker.sourceInstance || ''));
            lines.push('        bundle: ' + q(marker.bundleId || ''));
            lines.push('        bundle_center_offset: ' + String(Number(marker.bundleCenterOffset || marker.offset || 0).toFixed(4)));
            lines.push('        bundle_span: ' + n(marker.bundleSpan || 0));
          }
        }
        lines.push('    sources:');
        if (!modulePlan.sources.length) lines.push('      []');
        else {
          for (var s = 0; s < modulePlan.sources.length; s++) lines.push('      - ' + q(modulePlan.sources[s].name || 'SSNPadSource'));
        }
        lines.push('    bundles:');
        if (!modulePlan.bundles || !modulePlan.bundles.length) lines.push('      []');
        else {
          for (var b = 0; b < modulePlan.bundles.length; b++) {
            var bundle = modulePlan.bundles[b];
            lines.push('      - id: ' + q(bundle.id));
            lines.push('        side: ' + q(bundle.side));
            lines.push('        center_offset: ' + String(Number(bundle.centerOffset || 0).toFixed(4)));
            lines.push('        span: ' + n(bundle.span || 0));
            lines.push('        role: ' + q(bundle.role || ''));
          }
        }
      }
    }
    lines.push('');
    lines.push('chains:');
    if (!analysis.interfacePlan.chains.length) {
      lines.push('  []');
    } else {
      for (var c = 0; c < analysis.interfacePlan.chains.length; c++) {
        var chain = analysis.interfacePlan.chains[c];
        lines.push('  - id: ' + q(chain.id));
        lines.push('    source_module: ' + q(chain.sourceModuleName || ''));
        lines.push('    pair_count: ' + chain.pairs.length);
        lines.push('    bundle_count: ' + ((chain.bundles && chain.bundles.length) || 0));
      }
    }
    lines.push('');
    lines.push('generation:');
    lines.push('  generated_at: ' + q(new Date().toISOString()));
    return lines.join('\n');
  };
})(typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : this));
